Used PowerShell to remove lines with '#'.
Need to research this error when running:
PS C:\Users\Bruce\Programming\PythonLearning> & C:/Users/Bruce/AppData/Local/Programs/Python/Python310/python.exe c:/Users/Bruce/Programming/PythonLearning/CodeWars/valid_parentheses_from_outfile.py
  File "c:\Users\Bruce\Programming\PythonLearning\CodeWars\valid_parentheses_from_outfile.py", line 0

    ^
SyntaxError: unknown parsing error